return {
	require("plugins.ui.alpha"),
	require("plugins.ui.markdown"),
	require("plugins.ui.catppuccin"),
	require("plugins.ui.commander"),
	require("plugins.ui.headlines"),
	require("plugins.ui.neck-pain"),
	require("plugins.ui.colorizer"),
	require("plugins.ui.noice"),
	require("plugins.ui.lualine"),
	require("plugins.ui.todo-comments"),
	require("plugins.ui.image"),
	{ "stevearc/dressing.nvim" },
	require("plugins.ui.indent-scope"),
}
