return {
	require("plugins.ui.alpha"),
	require("plugins.ui.catppuccin"),
	require("plugins.ui.colorizer"),
	require("plugins.ui.helpview"),
	require("plugins.ui.image"),
	require("plugins.ui.indent-scope"),
	require("plugins.ui.lualine"),
	require("plugins.ui.markdown"),
	require("plugins.ui.neck-pain"),
	require("plugins.ui.noice"),
	require("plugins.ui.notify"),
	require("plugins.ui.whichkey"),
	require("plugins.ui.smear-cursor"),
	{ "stevearc/dressing.nvim" },
}
